sudo: required
services:
  # - mysql # do not add this line
  - docker

before_install:
  - docker-compose up -d

script:
  - sudo find / -type s
  - docker exec -it mysql-socket mysql -u root -ptest123 test < init.sql
  - echo finished