version: "3.1"
services:
  mysql:
    image: mysql:5.7.30
    container_name: mysql-socket
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: test
    ports:
      - 3307:3306


